# Generated by Django 5.0.6 on 2024-06-09 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sschscdetails',
            name='passing_year',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Passing Year.', regex='^(19\\d{2}|20[0-9]{2})$')]),
        ),
        migrations.AlterField(
            model_name='sschscdetails',
            name='percentage',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Percentage.', regex='^100(\\.0{1,2})?$|^(\\d{1,2}(\\.\\d{1,2})?)$')]),
        ),
    ]
