# Generated by Django 4.2.13 on 2024-06-11 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0002_alter_sschscdetails_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sschscdetails',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_form.basicdetails'),
        ),
    ]
