# Generated by Django 4.2.13 on 2024-06-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0004_alter_languageknown_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologiesknown',
            name='level_of_expertise',
            field=models.CharField(choices=[('beginner', 'Begineer'), ('mediator', 'Mediator'), ('expertise', 'Expertise')], max_length=9),
        ),
    ]
