# Generated by Django 4.2.13 on 2024-06-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0005_alter_technologiesknown_level_of_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_form.basicdetails'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_form.basicdetails'),
        ),
        migrations.AlterField(
            model_name='technologiesknown',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_form.basicdetails'),
        ),
    ]
