# Generated by Django 4.2.13 on 2024-06-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0006_alter_preference_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageknown',
            name='can_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='languageknown',
            name='can_speak',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='languageknown',
            name='can_write',
            field=models.BooleanField(default=False),
        ),
    ]
