# Generated by Django 4.2.13 on 2024-06-12 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0009_alter_languageknown_language_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_form.basicdetails'),
        ),
    ]
