# Generated by Django 4.2.13 on 2024-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0010_alter_workexperience_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_city_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=120)),
                ('city_state', models.CharField(max_length=120)),
            ],
        ),
    ]
