# Generated by Django 4.2.13 on 2024-06-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0011_state_city_master'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State_city_master',
            new_name='StateCityMaster',
        ),
    ]
