# Generated by Django 4.2.13 on 2024-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0013_alter_basicdetails_cities_alter_basicdetails_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='cities',
            field=models.CharField(max_length=20),
        ),
    ]
