# Generated by Django 4.2.13 on 2024-06-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0017_alter_basicdetails_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='states',
            field=models.CharField(choices=[('Hariyana', 'Hariyana'), ('Goa', 'Goa')], max_length=25),
        ),
    ]
