# Generated by Django 4.2.13 on 2024-06-07 08:02

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_basicdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='phone',
            field=models.CharField(validators=[form.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='zip',
            field=models.CharField(validators=[form.models.validate_zip]),
        ),
    ]
