# Generated by Django 4.2.13 on 2024-06-07 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_basicdetails_phone_alter_basicdetails_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='date_of_birth',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Date of Birth.', regex='^(0?[1-9]|[12][0-9]|3[01])[\\/\\-](0?[1-9]|1[012])[\\/\\-]\\d{4}$')]),
        ),
    ]
