# Generated by Django 4.2.13 on 2024-06-07 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_basicdetails_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSCHSCDETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_board', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Board name.', regex='^[a-zA-Z\\s-]+$')])),
                ('passing_year', models.IntegerField(validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Board name.', regex='^(19\\d{2}|20[0-9]{2})$')])),
                ('percentage', models.FloatField(validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Percentage.', regex='^100(\\.0{1,2})?$|^(\\d{1,2}(\\.\\d{1,2})?)$')])),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.basicdetails')),
            ],
        ),
    ]
