# Generated by Django 4.2.13 on 2024-06-07 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_sschscdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sschscdetails',
            name='passing_year',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Passing Year.', regex='^(19\\d{2}|20[0-9]{2})$')]),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Company name.', regex='^[a-zA-Z\\s-]+$')])),
                ('designation', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Designation name.', regex='^[a-zA-Z\\s-]+$')])),
                ('_from', models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Date.', regex='^(0?[1-9]|[12][0-9]|3[01])[\\/\\-](0?[1-9]|1[012])[\\/\\-]\\d{4}$')])),
                ('_to', models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Date .', regex='^(0?[1-9]|[12][0-9]|3[01])[\\/\\-](0?[1-9]|1[012])[\\/\\-]\\d{4}$')])),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.basicdetails')),
            ],
        ),
    ]
