# Generated by Django 4.2.13 on 2024-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_sschscdetails_passing_year_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='_to',
            field=models.DateField(),
        ),
    ]
