# Generated by Django 4.2.13 on 2024-06-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_workexperience__from_alter_workexperience__to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
