# Generated by Django 4.2.13 on 2024-06-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_alter_basicdetails_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='relationship',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=8),
        ),
        migrations.CreateModel(
            name='LanguageKnown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_known', models.CharField(choices=[('hindi', 'Hindi'), ('gujarati', 'Gujarati'), ('english', 'English')], max_length=15)),
                ('can_read', models.BooleanField()),
                ('can_write', models.BooleanField()),
                ('can_speak', models.BooleanField()),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.basicdetails')),
            ],
        ),
    ]
