# Generated by Django 4.2.13 on 2024-06-07 10:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_technologiesknown_level_of_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid  name.', regex='^[a-zA-Z\\s-]+$')])),
                ('contact_no', models.CharField(validators=[form.models.validate_phone])),
                ('Relation', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid  name.', regex='^[a-zA-Z\\s-]+$')])),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.basicdetails')),
            ],
        ),
    ]
