# Generated by Django 4.2.13 on 2024-06-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_location', models.TextField()),
                ('notice_period', models.CharField(max_length=15)),
                ('expected_ctc', models.CharField(max_length=15)),
                ('current_ctc', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('development', 'Development'), ('department', 'Department'), ('marketing', 'Marketing')], max_length=25)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.basicdetails')),
            ],
        ),
    ]
