# Generated by Django 4.2.13 on 2024-06-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_basicdetails_cities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='_from',
            new_name='from1',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='_to',
            new_name='to1',
        ),
    ]
