# Generated by Django 4.2.13 on 2024-06-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_rename__from_workexperience_from1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sschscdetails',
            name='name_of_board',
            field=models.CharField(choices=[('GSEB', 'GSEB'), ('CBSC', 'CBSC'), ('Bachelor_Degree', 'Bachelor_Degree'), ('Master_Degree', 'Master_Degree'), ('PHD', 'PHD')], default=None, max_length=15),
        ),
    ]
